let RolesList = {
    WAREHOUSE_OWNER:"WAREHOUSE_OWNER",
    VOLUNTEER:"VOLUNTEER",
    USER:"USER",
    COMPANY:"COMPANY",
    WAREHOUSE_CLIENT:"WAREHOUSE_CLIENT",
    DRIVER:"DRIVER",
    CLIENT:"CLIENT",
    ADMIN:"ADMIN",
    WEBSITE_OWNER:"WEBSITE_OWNER",
    ROOT:"ROOT"
}

export default RolesList;