let StatusesList = {
    TO_DO: 'TO_DO',
    COMPLETE: 'COMPLETE',
    ACCEPTED: 'ACCEPTED',
    BANNED: 'BANNED',
    WAITING_FOR_PAY: 'WAITING_FOR_PAY',
    CANCELLED: 'CANCELLED',
    WAITING_FOR_RATE_CLIENT: 'WAITING_FOR_RATE_CLIENT',
    PENDING: 'PENDING',
    NEW: 'NEW',
    CLOSED: 'CLOSED',
    WAITING_FOR_RATE_CUSTOMER: 'WAITING_FOR_RATE_CUSTOMER',
    PAID: 'PAID',
    REJECTED: 'REJECTED',
    START:'START',
    END:'END'
}
export default StatusesList;